config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#about'
  
   get 'emails/new', to:'emails#new'
   get 'emails', to:'emails#new'
   
  get 'projects', to:'pages#projects'
 
  get 'contact', to:'pages#contact'

   get 'thankyou', to:'pages#thankyou'
 resources :emails
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
     before_save { self.email = email.downcase }
     validates :name, presence: true, length: { maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
     validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
     validates :phone, presence: true, length: { maximum: 10 }
     validates :content, presence: true, length: { maximum: 1000 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def index
    redirect_to new_email_url
  end

  def new
    @email = Email.new
  end
  
  def create
    @email = Email.new(email_params)
    if @email.save
      EmailMailer.new_email(@email).deliver_now
      flash[:info] = "Thank you for the email, we will get back to you shortly!!!"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  

  private

    def email_params
      params.require(:email).permit(:name, :email, :phone,
                                   :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   
   def index
   end
   
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def index
   end
   
   def contact
   end
   
   def about
   end
   
   def services
   end
   
   def thankyou
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/views/home/_home.html.erb
<h1 style="text-align:center;"> <i>Freelance Web and Mobile Developer based in Maryland, USA.<br> Highly experienced in developing web and mobile applications.</i></h1>
<br>

<div class="jumbotron jumbotron-fluid" id="services-jumbo">
  <div class="container">
  </div>
</div>

<h3 style="text-align:center;">Our Services</h3>
<div class="row">

<div class="card col-sm-4" style="width: 20rem;">
  <%= image_tag("services/web.jpeg", :alt => "rss feed", :class => "card-img-top card-image-resize") %>
  <div class="card-block ">
    <h4 class="card-title">Web Development</h4>
    <p class="card-text">Our approach to website design is to create a website that strengthens your company’s brand while 
    ensuring ease of use and simplicity for your audience.</p>
   <a <%= link_to "Get Quote", new_email_path, class: "btn btn-primary" %></a>
  </div>
</div>

<div class="card col-sm-4" style="width: 20rem;">
  <%= image_tag("services/WP.png", :alt => "rss feed", :class => "card-img-top card-image-resize") %>
  <div class="card-block ">
    <h4 class="card-title">Wordpress</h4>
    <p class="card-text">We have experience in Wordpress, Wix and Weebly and will quickly design sites for you. Each site is SEO optimized for best performance as well.</p>
    <a <%= link_to "Get Quote", new_email_path, class: "btn btn-primary" %></a>
  </div>
</div>

<div class="card col-sm-4" style="width: 20rem;">
  <%= image_tag("services/ios.png", :alt => "rss feed", :class => "card-img-top card-image-resize") %>
  <div class="card-block">
    <h4 class="card-title">Apple Apps</h4>
    <p class="card-text">Our approach is to create an app design that strengthens your company’s brand while ensuring ease of use and simplicity for your audience.</p>
    <a> <%= link_to "Get Quote", new_email_path, class: "btn btn-primary" %></a>
  </div>
</div>

</div>

<div class="container">
<br>
<h3 style="text-align: center;"> <Strong>Why Us?</Strong></h3>
<br>
<h4> Affordable</h4>
<p>One of the most obvious reasons why businesses are hiring more and more freelance developers is that it is very cost-effective to do so. You can hire freelance web developers within your budget without compromising on quality .</p>
<h4> Trust The Process</h4>
<p>When tasked with a new project our team has developed a system that has proven to be most efficient and time saving. We use wireframing and sketches of every application and ensure that's what our client wants. While developing we regularly update the client and provide feedback and tips to improve the project. We believe strong communication with the client is a key driver to success, so we have made ourselves easy to reach! Lastly, we care about the success of our clients. We understand 
the possible complications that may arise from ambiguity and pledge to be as patient as needed for the success of the project.</p>
</div>
<a> <%= link_to "Projects", projects_path, class: "btn btn-info" %></a>
</div>
         

app/views/home/index.html.erb
<div class="fixed-container">
<h1> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean dictum risus a felis finibus pharetra. Nam libero turpis, varius sed sapien fringilla, pharetra ullamcorper risus. Cras erat metus, cursus vitae nisi sit amet, consequat rhoncus libero. In porta urna nec urna tincidunt, ut lobortis lectus gravida. Fusce fermentum, purus et porttitor accumsan, urna nibh convallis risus, vitae egestas felis dolor quis ex. Nulla sagittis facilisis neque, eu viverra nulla semper eget. Aenean leo quam, efficitur egestas venenatis cursus, dignissim a massa. Ut lorem enim, semper eu blandit eu, rhoncus eu mi. Suspendisse sit amet purus non nulla dictum tempor non et nisi. Vivamus eget aliquet urna. Cras placerat tellus id odio dapibus tristique.

Sed sodales libero quis tellus congue, vel ultrices augue posuere. In rutrum vehicula turpis. Nam commodo rutrum massa sed venenatis. Nunc fringilla massa id libero suscipit viverra. Proin elementum nunc id nulla vehicula ullamcorper. Fusce fringilla dignissim egestas. Nunc eget lacus turpis. Mauris ullamcorper metus eros. Duis aliquet consequat diam, in venenatis ante commodo sit amet. Duis facilisis, nisi dictum convallis pretium, eros dui commodo massa, non pharetra odio justo condimentum ipsum. Fusce bibendum vestibulum risus, porta auctor risus ullamcorper non.

Pellentesque eget hendrerit mauris, eget consectetur arcu. Maecenas placerat id purus sit amet tristique. Cras fermentum mi ut sem blandit, ut posuere libero hendrerit. Aenean eleifend nisi id eros mattis, ac lacinia elit maximus. Maecenas finibus sollicitudin massa, eget tempus lectus pulvinar a. Ut pretium accumsan malesuada. Curabitur vel sapien odio. Nunc tincidunt sit amet nunc et feugiat. Pellentesque pharetra ipsum at consequat finibus. Maecenas sodales, elit eu vulputate feugiat, diam erat semper augue, ac congue sem nisi sed neque. Etiam lacus eros, faucibus et nisi id, pulvinar euismod mauris. Nam finibus imperdiet leo.

Phasellus convallis aliquet mi varius sagittis. Nam pharetra risus nisi, ut aliquam ipsum ultrices in. Integer sed diam ultrices, eleifend massa quis, venenatis mi. Donec in posuere libero, vel interdum libero. Nunc tristique volutpat convallis. Donec ac mi a ligula iaculis gravida. Pellentesque ut quam faucibus sapien tempor dictum nec eleifend erat. Curabitur sed sem placerat, sagittis dui at, porta velit. Morbi placerat felis quis malesuada porta. Nam mattis cursus sem, a dapibus erat interdum ac. Sed ante velit, faucibus non ex ornare, interdum gravida dui.

Cras ac vestibulum risus. Nam pellentesque consequat nisi sed vulputate. Maecenas vulputate, ligula sit amet luctus suscipit, enim orci venenatis odio, non tincidunt ex massa vitae tortor. Nulla sit amet ante tortor. Aliquam rhoncus scelerisque purus, in scelerisque ex vulputate faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur maximus hendrerit odio a pulvinar.</h1>
</div>

app/views/layouts/_navigation.html.erb
<div class="side-navigation">
  <%= image_tag("prof-img.png", class: "portrait") %>
  <h2 ><%= link_to "Home", root_path, id: "color-fade" %></h2>
 
  <ul class="list" >
  <li ><a id = "color-fade" href="https://docs.google.com/document/d/1sITeSY6M3H9dKf_4q1Th6BUNl0-ErVQ1yvJ7BCeaWnw/edit?usp=sharing" target="_blank">Resume</a></li>
  <li ><a id = "color-fade" href="../projects">Projects</a></li>
  <li ><a id = "color-fade" href="../emails/new">Contact</a></li>
  </ul>
  
  <a href="https://www.facebook.com/dylan.godfrey.1" target="_blank"> <%= image_tag("fbicon.png", class: "icon") %>   </a>
  <a href="https://www.linkedin.com/in/dylan-godfrey-3840b5121" target="_blank"> <%= image_tag("linkedin.png", class: "icon") %>   </a>
   <a href="https://github.com/dylangodfrey12" target="_blank"> <%= image_tag("github.png", class: "icon") %>   </a>
  <br><br><br><br><br>
  <p style="color: white;"><em> "A good programmer looks both ways before crossing a one-way street"</em></p>
  
  <p style="color: white;"><em>-Yours Truly</em></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DAG Apps and Web Development</title>
    <%= csrf_meta_tags %>
  <%= tag :meta, name: :psj, action: action_name, controller: controller_name %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body >
    <%= render 'layouts/navigation' %>
<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="fixed-container styling" style="backgroud-color: light-text;">
   <h1 style="text-align:center;">Portfolio</h1>
<div >
  <%= image_tag("about.png", :alt => "rss feed", :class => "about-img") %>
 </div>
 
 

<h4>My Story... </h4>
    <p class = 'portfolio-text'> I currently have experience developing both IOS and Android applications and Websites. I am a junior full stack Web Developer that uses JavaScript, HTML,CSS for front-end development, and Ruby, ReactJs, JS, SASS and ruby for back-end development on the Rails platform. I also can aid in web development from platforms such as Wordpress, Wix, foursquare, Shopify and Weebly.
    <br><br>
    I have roughly 2-4 years of experience coding and I am continually improving!

<br><br><strong>I am ambitious and eager to learn new things from unique challenges.</strong><br><br> My education consists of self taught computer science since 2014, an engineering degree from The Pennsylvania State University in 2017 and consistently taking online courses to aid my knowledge such as Harvard X, Code Academy and UDemy. 


Communication is a priority to me. It removes all ambiguity from projects which will aid in the completion of my products. I am very adaptable and can communicate in any way that is best for you. I speak fluent english and can read and write in French or Spanish if needed. I am looking forward to working with new clients and advancing my skills.</p>


</div>

app/views/pages/projects.html.erb
<h2 style="margin: 0px auto 5px;">     Websites recently created </h2>
<p style="margin:  auto 5px;">    Languages: HTML/CSS, Javascript, Ruby, Swift and Java</p>

<div class="container">
  
  <%= image_tag("blogsample.png", :alt => "rss feed", :class => "image", :style => "width: 100%") %>
  
  <div class="middle">
    <div class="text">
       <h5> Twitter(like) Blog Site</h5>
       <ul>
          <li>HTML 5 (layout)</li>
          <li>Javascript/Ajax (frontend functionality) </li>
          <li>Ruby & Ruby on Rails (backend) </li>
       </ul>
    </div>
  </div>
</div>
<div class="container">
  
  <%= image_tag("financesample.png", :alt => "rss feed", :class => "image", :style => "width: 100%") %>
  
  <div class="middle">
    <div class="text">
     <h5> Stock Tracker App</h5>
     <p> Simple web application to keep track of stocks with google stock api integrated</p>
       <ul>
          <li>HTML 5/bootstrap (layout)</li>
          <li>Ajax (frontend functionality) </li>
          <li>Ruby & Ruby on Rails (backend) </li>
       </ul>
    </div>
  </div>
</div>
<h2>Live Sites</h2>
<p>Hover over the image to see the effect.</p>

<div class="container">
  
  <%= image_tag("landscapesample.png", :alt => "rss feed", :class => "image", :style => "width: 100%") %>
  
  <div class="middle">
    <div class="text">
        <h5> Professional Business Site for Contractor</h5>
       <ul>
          <li>HTML/CSS (layout)</li>
          <li>Javascript/Ajax (frontend functionality) </li>
          <li>Ruby & Ruby on Rails (backend) </li>
       </ul>
       </div>
  </div>
</div>
<div class="container">
  
  <%= image_tag("wixsample.png", :alt => "rss feed", :class => "image", :style => "width: 100%") %>
  
  <div class="middle">
    <div class="text">
     <h5> Wix Site</h5>
       <ul>
          <li>Wix Framework </li>
          
       </ul></div>
  </div>
</div>
<div class="container">
  
  <%= image_tag("wpsample.png", :alt => "rss feed", :class => "image", :style => "width: 100%") %>
  
  <div class="middle">
    <div class="text">
     <h5> Wordpress Site IOS/Android APP</h5>
     <p> Two apps created to aggregate information from Blog site</p>
       <ul>
          <li>Swift(IOS) Java(Android) application</li>
          <li>SQL (database)<li>
       </ul></div>
  </div>
</div>